from pydantic import BaseModel, Field
from typing import List

class ConductorWorkflow(BaseModel):
    """
    The dynamic coordination strategy produced by the Conductor.
    It specifies which models to query, what subtasks to give them,
    and the communication topology (who sees what).
    """
    needs_clarification: bool = Field(
        default=False,
        description="Set to true if the user's request is ambiguous or lacks necessary details to formulate a solid plan."
    )
    clarification_question: str | None = Field(
        default=None,
        description="The question to ask the user if needs_clarification is true."
    )
    model_id: List[int] = Field(
        description="The integers corresponding to the numbered language models in the sequence you want to prompt."
    )
    subtasks: List[str] = Field(
        description="The string prompts defining the specific subtask for the corresponding language model."
    )
    access_list: List[List[str]] = Field(
        description="Lists specifying past responses to include in the context. E.g., ['all'] for everything, or [] for isolated execution."
    )

class WorkerResponse(BaseModel):
    """
    The structured output generated by a dynamic Worker Agent executing a subtask.
    """
    response: str = Field(
        description="The detailed response or code implementation for the assigned subtask."
    )
    proposed_patch: str | None = Field(
        default=None,
        description="A unified diff format patch if the subtask involved modifying code."
    )
